name: Document undocumented code

on:
  push:
    branches:
      - main
jobs: 
  code-documentation:
    runs-on: ubuntu-latest      
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Document Code
        uses: mystral-ai/feat/make-installable
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          path: ${{ github.workspace }}
          recursive: true
          target_branch: main
